server:
  port: 8800
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cxw?setUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 5 # 最小空闲连接数量
      maximum-pool-size: 25 # 连接池最大连接数，默认是10
      idle-timeout: 180000 # 空闲连接存活最大时间，默认600000（10分钟)
      auto-commit: true # 自动提交事务
      max-lifetime: 1800000 #最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  application:
    name: account
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/**/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl